// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class DimBusinessorg
    {
        public int? EntCountryGroupOid { get; set; }
        public int? EntCountryGroupLoid { get; set; }
        public int? EntCountryOid { get; set; }
        public int? EntCountryLoid { get; set; }
        public int? EntGroupOid { get; set; }
        public int? EntGroupLoid { get; set; }
        public int? EntEntityOid { get; set; }
        public int? EntEntityLoid { get; set; }
        public int? EntSubGroupOid { get; set; }
        public int? EntSubGroupLoid { get; set; }
        public int? EntSiteOid { get; set; }
        public int? EntSiteLoid { get; set; }
        public DateTime? DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
        public int? EditLevel { get; set; }
        public string Dlevel { get; set; }
        public int? Oid { get; set; }
        public int Id { get; set; }
        public int? CusParentCustomerOid { get; set; }
        public int? CusParentCustomerLoid { get; set; }
        public int? CusRegionOid { get; set; }
        public int? CusRegionLoid { get; set; }
        public int? CusCustomerCategoryOid { get; set; }
        public int? CusCustomerCategoryLoid { get; set; }
        public int? CusOutletGroupOid { get; set; }
        public int? CusOutletGroupLoid { get; set; }
        public int? CusOutletVpoClassOid { get; set; }
        public int? CusOutletVpoClassLoid { get; set; }
        public int? CusOutletCmgVerticalOid { get; set; }
        public int? CusOutletCmgVerticalLoid { get; set; }
        public int? CusOutletCmgClassOid { get; set; }
        public int? CusOutletCmgClassLoid { get; set; }
        public int? CusOutletTradeTypeOid { get; set; }
        public int? CusOutletTradeTypeLoid { get; set; }
        public int? CusCustomerOid { get; set; }
        public int? CusCustomerLoid { get; set; }
        public int? CusTownClassOid { get; set; }
        public int? CusTownClassLoid { get; set; }
        public int? EntMasterGroupOid { get; set; }
        public int? EntMasterGroupLoid { get; set; }
    }
}