// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class DimBusinessorg
    {
        public int? EntCountryGroupOid { get; set; }
        public int? EntCountryGroupLoid { get; set; }
        public int? EntCountryOid { get; set; }
        public int? EntCountryLoid { get; set; }
        public int? EntGroupOid { get; set; }
        public int? EntGroupLoid { get; set; }
        public int? EntEntityOid { get; set; }
        public int? EntEntityLoid { get; set; }
        public int? EntSubGroupOid { get; set; }
        public int? EntSubGroupLoid { get; set; }
        public int? EntSiteOid { get; set; }
        public int? EntSiteLoid { get; set; }
        public DateTime? DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
        public int? EditLevel { get; set; }
        public string Dlevel { get; set; }
        public int? Oid { get; set; }
        public int Id { get; set; }
        public int? CusCustomerLoid { get; set; }
        public int? EntMasterGroupOid { get; set; }
        public int? EntMasterGroupLoid { get; set; }
    }
}