// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Dimension
    {
        public string FlattenedTableName { get; set; }
        public string DimensionName { get; set; }
        public string DisplayName { get; set; }
        public int EditLevel { get; set; }
    }
}