// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class EntityTypeAttr
    {
        public int EntityTypeId { get; set; }
        public string AttrName { get; set; }
        public string AttrDataType { get; set; }
        public int ColumnSequence { get; set; }
        public bool IsMandatoryFlag { get; set; }
        public string Derivation { get; set; }
        public int AttrLength { get; set; }
        public bool? AttrPrecision { get; set; }
        public bool IsPartOfCode { get; set; }
        public bool? IsDerived { get; set; }
        public int EditLevel { get; set; }
        public int? ParentEntityTypeId { get; set; }
        public string ListBoxQuery { get; set; }
        public string AttrDisplayName { get; set; }
        public string AttrDisplayOrder { get; set; }
        public string DisplayType { get; set; }
        public bool? IsSearchable { get; set; }
        public bool? IsListable { get; set; }
        public string HistoryQuery { get; set; }
        public bool? IsHyperlinked { get; set; }
        public string Isvisible { get; set; }
        public string CasQuery { get; set; }
        public string CasDrop { get; set; }
    }
}