// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class EntityType
    {
        public int Id { get; set; }
        public int EditLevel { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string DimensionName { get; set; }
        public string InputTableName { get; set; }
        public bool IsStrongEntity { get; set; }
        public bool IsManyToMany { get; set; }
        public bool IsSubType { get; set; }
        public bool IsSuperType { get; set; }
        public bool DefaultSortBy { get; set; }
        public string DefaultSortOrder { get; set; }
        public string DimensionDisplayName { get; set; }
        public string DisplayOrder { get; set; }
    }
}