// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class EntityTypeRelation
    {
        public int EntityTypeId { get; set; }
        public int ParentEntityTypeId { get; set; }
        public int? IsMandatoryFlag { get; set; }
        public int? IsIdentifyingRelation { get; set; }
        public int EditLevel { get; set; }
        public int? ToBeFlattened { get; set; }
        public int? IsTimeVariantFlag { get; set; }
        public int? FlatFlag { get; set; }
    }
}