// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class EntityTypeAttrLov
    {
        public int EntityTypeId { get; set; }
        public string AttrName { get; set; }
        public string ValidValues { get; set; }
        public string ValueName { get; set; }
        public string SortOrder { get; set; }
    }
}