// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Model.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Model.Models
{
    public partial interface IMPP_ContextProcedures
    {
        Task<List<GET_MPP_WORKFLOW_SAVEResult>> GET_MPP_WORKFLOW_SAVEAsync(string i_Session_Id, int? i_entity_type_id, string i_Approver_Id, string i_status, OutputParameter<int?> resultval, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> GET_VIEW_NAMEAsync(int? i_entity_type_id, string i_user_id, OutputParameter<string> view_name, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> MPP_ENTITY_SEC_BASE_VIEWS_FN_PROCAsync(int? I_ENTITY_TYPE_ID, string I_USER_ID, OutputParameter<string> I_RESULT, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> MPP_ENTITY_USER_SEC_VIEWS_LOVAsync(int? i_entity_type_id, string i_user_id, OutputParameter<string> i_result, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<MPP_LOAD_CHKResult>> MPP_LOAD_CHKAsync(string i_Session_id, string i_entity_type_id, string i_user_id, decimal? i_suppress_warnings, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<MPP_REFRESH_ROW_SECURITYResult>> MPP_REFRESH_ROW_SECURITYAsync(string I_USER_ID, string I_ENTITY_ID, string I_DIM, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
