// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class LoadEntity
    {
        public DateTime? DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
        public string EntSiteCode { get; set; }
        public string EntSiteLongName { get; set; }
        public string EntSiteShortName { get; set; }
        public string DummyFlag { get; set; }
        public string ActiveFlag { get; set; }
        public DateTime? EffectiveStartDate { get; set; }
        public DateTime? EffectiveEndDate { get; set; }
        public string SourceSystemCode { get; set; }
        public int? SortOrder { get; set; }
        public string ErrorMessage { get; set; }
        public string WarningMessage { get; set; }
        public string SessionId { get; set; }
        public TimeSpan? CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UpdatedUserid { get; set; }
        public int? RowSecFlag { get; set; }
        public string ApproverId { get; set; }
        public string UserId { get; set; }
        public string Comments { get; set; }
        public string UserLevel { get; set; }
        public string ApproverLevel { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastUpdateTime { get; set; }
        public int? LdOid { get; set; }
        public int? RowStatus { get; set; }
        public string LocationName { get; set; }
        public string OtherLocationName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string Pincode { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public string AssocciateName { get; set; }
        public string Remarks { get; set; }
        public int? RecLockFlag { get; set; }
        public int? TreatNullsAsNulls { get; set; }
        public int? CurrentEditLevel { get; set; }
        public string EntSiteDesc { get; set; }
        public string SiteType { get; set; }
        public int InputRowId { get; set; }
        public string EntSubGroupCode { get; set; }
        public string Validationcode { get; set; }
        public string ApproverStatus { get; set; }
    }
}