// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class LoadEntity
    {
        public DateTime? DateFrom { get; set; }
        public int? SortOrder { get; set; }
        public string OsgOutletSegmentGroupCode { get; set; }
        public string OsgOutletSegmentGroupLongName { get; set; }
        public string OsgOutletSegmentGroupShortName { get; set; }
        public string DummyFlag { get; set; }
        public string ActiveFlag { get; set; }
        public string SourceSystemName { get; set; }
        public int? TreatNullsAsNulls { get; set; }
        public int? CurrentEditLevel { get; set; }
        public string ErrorMessage { get; set; }
        public string WarningMessage { get; set; }
        public string SessionId { get; set; }
        public int? InputRowId { get; set; }
        public TimeSpan? CreatedOn { get; set; }
        public int? RowSecFlag { get; set; }
        public string ApproverId { get; set; }
        public string UserId { get; set; }
        public string Comments { get; set; }
        public int? UserLevel { get; set; }
        public int? ApproverLevel { get; set; }
        public string ApproverStatus { get; set; }
        public int? LdOid { get; set; }
        public int? RowStatus { get; set; }
        public int? RecLockFlag { get; set; }
        public string ProductGroupId { get; set; }
    }
}