// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models
{
    public partial class MPP_REFRESH_ROW_SECURITYResult
    {
        [Column("Error Message")]
        public int? ErrorMessage { get; set; }
    }
}
