// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class MppConfig
    {
        public string ParamValue { get; set; }
        public string ParamName { get; set; }
    }
}