// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Querytext2
    {
        public int? EntityTypeId { get; set; }
        public string EntityInternalCode { get; set; }
        public string MandatoryAttrErrMesg { get; set; }
        public string ErrorMessage { get; set; }
        public string WarningMessage { get; set; }
        public string Vc3 { get; set; }
        public string Vc2 { get; set; }
        public string Vc1 { get; set; }
        public int? N1 { get; set; }
        public string SuppliedCode1 { get; set; }
        public string Vc0 { get; set; }
        public string SuppliedCode2 { get; set; }
        public string SuppliedCode3 { get; set; }
        public string SuppliedCode4 { get; set; }
        public string SuppliedCode5 { get; set; }
        public string Vc4 { get; set; }
        public string Vc5 { get; set; }
        public string Vc6 { get; set; }
        public string Vc7 { get; set; }
        public string Vc8 { get; set; }
        public string Vc9 { get; set; }
        public string Vc10 { get; set; }
        public string Vc11 { get; set; }
        public string Vc12 { get; set; }
        public string Vc13 { get; set; }
        public string Vc14 { get; set; }
        public string Vc15 { get; set; }
        public int? N2 { get; set; }
        public int? N3 { get; set; }
        public int? N4 { get; set; }
        public int? N5 { get; set; }
        public int? N6 { get; set; }
        public int? N7 { get; set; }
        public int? N8 { get; set; }
        public int? N9 { get; set; }
        public int? N10 { get; set; }
        public int? N11 { get; set; }
        public int? N12 { get; set; }
        public int? N13 { get; set; }
        public int? N14 { get; set; }
        public int? N15 { get; set; }
        public DateTime? Dt1 { get; set; }
        public DateTime? Dt2 { get; set; }
        public DateTime? Dt3 { get; set; }
        public DateTime? Dt4 { get; set; }
        public DateTime? Dt5 { get; set; }
        public DateTime? Dt6 { get; set; }
        public DateTime? Dt7 { get; set; }
        public DateTime? Dt8 { get; set; }
        public DateTime? Dt9 { get; set; }
        public DateTime? Dt10 { get; set; }
        public DateTime? DateFrom { get; set; }
        public int? SessionId { get; set; }
        public int? InputRowId { get; set; }
        public string SourceSystemCode { get; set; }
        public int? TreatNullsAsNulls { get; set; }
        public int? CurrentEditLevel { get; set; }
    }
}