// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Querytext2
    {
        public int? EntityTypeId { get; set; }
        public string EntityInternalCode { get; set; }
        public string MandatoryAttrErrMesg { get; set; }
        public string ErrorMessage { get; set; }
        public string WarningMessage { get; set; }
        public string Vc3 { get; set; }
        public string Vc2 { get; set; }
        public string Vc1 { get; set; }
        public int? N1 { get; set; }
        public string SuppliedCode1 { get; set; }
        public string Vc0 { get; set; }
        public string SuppliedCode2 { get; set; }
        public string SuppliedCode3 { get; set; }
        public string SuppliedCode4 { get; set; }
        public string SuppliedCode5 { get; set; }
        public string Vc4 { get; set; }
        public string Vc5 { get; set; }
        public string Vc6 { get; set; }
        public string Vc7 { get; set; }
        public string Vc8 { get; set; }
        public string Vc9 { get; set; }
        public string Vc10 { get; set; }
        public string Vc11 { get; set; }
        public string Vc12 { get; set; }
        public string Vc13 { get; set; }
        public string Vc14 { get; set; }
        public string Vc15 { get; set; }
        public int? N2 { get; set; }
        public int? N3 { get; set; }
        public int? N4 { get; set; }
        public int? N5 { get; set; }
        public int? N6 { get; set; }
        public int? N7 { get; set; }
        public int? N8 { get; set; }
        public int? N9 { get; set; }
        public int? N10 { get; set; }
        public int? N11 { get; set; }
        public int? N12 { get; set; }
        public int? N13 { get; set; }
        public int? N14 { get; set; }
        public int? N15 { get; set; }
        public DateTime? Dt1 { get; set; }
        public DateTime? Dt2 { get; set; }
        public DateTime? Dt3 { get; set; }
        public DateTime? Dt4 { get; set; }
        public DateTime? Dt5 { get; set; }
        public DateTime? Dt6 { get; set; }
        public DateTime? Dt7 { get; set; }
        public DateTime? Dt8 { get; set; }
        public DateTime? Dt9 { get; set; }
        public DateTime? Dt10 { get; set; }
        public DateTime? DateFrom { get; set; }
        public int? SessionId { get; set; }
        public int? InputRowId { get; set; }
        public string SourceSystemName { get; set; }
        public int? TreatNullsAsNulls { get; set; }
        public int? CurrentEditLevel { get; set; }
        public string Vc16 { get; set; }
        public string Vc17 { get; set; }
        public string Vc18 { get; set; }
        public string Vc19 { get; set; }
        public string Vc20 { get; set; }
        public string Vc21 { get; set; }
        public string Vc22 { get; set; }
        public string Vc23 { get; set; }
        public string Vc24 { get; set; }
        public string Vc25 { get; set; }
        public string Vc26 { get; set; }
        public string Vc27 { get; set; }
        public string Vc28 { get; set; }
        public string Vc29 { get; set; }
        public string Vc30 { get; set; }
        public string Vc31 { get; set; }
        public string Vc32 { get; set; }
        public string Vc33 { get; set; }
        public string Vc34 { get; set; }
        public string Vc35 { get; set; }
        public string Vc36 { get; set; }
        public string Vc37 { get; set; }
        public string Vc38 { get; set; }
        public string Vc39 { get; set; }
        public string Vc40 { get; set; }
        public string Vc41 { get; set; }
        public string Vc42 { get; set; }
        public string Vc43 { get; set; }
        public string Vc44 { get; set; }
        public string Vc45 { get; set; }
        public string Vc46 { get; set; }
        public string Vc47 { get; set; }
        public string Vc48 { get; set; }
        public string Vc49 { get; set; }
        public string Vc50 { get; set; }
    }
}