// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Querytexttype2
    {
        public string EntityInternalCode { get; set; }
        public int EntityTypeId { get; set; }
        public string ParentInternalCode { get; set; }
        public int ParentEntityTypeId { get; set; }
        public int? IsIdentifyingRelation { get; set; }
        public DateTime? DateFrom { get; set; }
        public string SessionId { get; set; }
        public int? InputRowId { get; set; }
        public string SourceSystemCode { get; set; }
        public int? TreatNullsAsNulls { get; set; }
        public int? CurrentEditLevel { get; set; }
        public string ErrorMessage { get; set; }
    }
}